import SwiftUI

private struct SearchCall: Decodable, Identifiable { let id: UUID; let callerName: String; let notes: String?; enum CodingKeys: String, CodingKey { case id, notes; case callerName = "caller_name" } }
private struct SearchNote: Decodable, Identifiable { let id: UUID; let title: String; let content: String? }
private struct SearchEvent: Decodable, Identifiable { let id: UUID; let title: String; let location: String? }
private struct SearchPayment: Decodable, Identifiable { let id: UUID; let paymentType: String; let recipient: String; enum CodingKeys: String, CodingKey { case id, recipient; case paymentType = "payment_type" } }
private struct SearchClient: Decodable, Identifiable { let id: UUID; let name: String; let company: String? }
private struct SearchResult: Identifiable { let id: UUID; let type: String; let title: String; let detail: String; let icon: String }

struct GlobalSearchView: View {
    @Environment(\.dismiss) private var dismiss
    @State private var query = ""; @State private var results: [SearchResult] = []
    let onOpen: (String, UUID) -> Void
    var body: some View { VStack(spacing: 0) { HStack { Image(systemName: "magnifyingglass").foregroundStyle(.secondary); TextField("Cerca in tutta AK Suite", text: $query).textFieldStyle(.plain); Button { dismiss() } label: { Image(systemName: "xmark.circle.fill").foregroundStyle(.secondary) } }.padding(14).background(Color(.secondarySystemBackground)).clipShape(RoundedRectangle(cornerRadius: 14)).padding(); List(results) { result in Button { onOpen(result.type, result.id); dismiss() } label: { Label { VStack(alignment: .leading) { Text(result.title); Text(result.detail).font(.caption).foregroundStyle(.secondary) } } icon: { Image(systemName: result.icon) } } }.listStyle(.plain) }.onChange(of: query) { _ in Task { await search() } }.presentationDetents([.fraction(0.45)]).presentationDragIndicator(.visible) }
    private func search() async { guard query.trimmingCharacters(in: .whitespaces).count >= 2 else { results = []; return }; let term = query.lowercased(); do { async let calls: [SearchCall] = SupabaseService.shared.from("calls").select().limit(100).execute().value; async let notes: [SearchNote] = SupabaseService.shared.from("notes").select().limit(100).execute().value; async let events: [SearchEvent] = SupabaseService.shared.from("events").select().limit(100).execute().value; async let payments: [SearchPayment] = SupabaseService.shared.from("payments").select().limit(100).execute().value; async let clients: [SearchClient] = SupabaseService.shared.from("clients").select().limit(100).execute().value; let found = try await (calls, notes, events, payments, clients); results = found.0.filter { "\($0.callerName) \($0.notes ?? "")".lowercased().contains(term) }.map { SearchResult(id: $0.id, type: "call", title: $0.callerName, detail: "Chiamata", icon: "phone") } + found.1.filter { "\($0.title) \($0.content ?? "")".lowercased().contains(term) }.map { SearchResult(id: $0.id, type: "note", title: $0.title, detail: "Nota", icon: "note.text") } + found.2.filter { "\($0.title) \($0.location ?? "")".lowercased().contains(term) }.map { SearchResult(id: $0.id, type: "event", title: $0.title, detail: "Evento", icon: "calendar") } + found.3.filter { "\($0.paymentType) \($0.recipient)".lowercased().contains(term) }.map { SearchResult(id: $0.id, type: "payment", title: $0.paymentType, detail: "Pagamento · \($0.recipient)", icon: "creditcard") } + found.4.filter { "\($0.name) \($0.company ?? "")".lowercased().contains(term) }.map { SearchResult(id: $0.id, type: "client", title: $0.name, detail: "Contatto", icon: "person") } } catch { results = [] } }
}