import SwiftUI

private struct TodayCall: Decodable, Identifiable { let id: UUID; let callerName: String; let followUp: Bool; let followUpDate: String?; let followUpTime: String?; enum CodingKeys: String, CodingKey { case id; case callerName = "caller_name"; case followUp = "follow_up"; case followUpDate = "follow_up_date"; case followUpTime = "follow_up_time" } }
private struct TodayEvent: Decodable, Identifiable { let id: UUID; let title: String; let startDate: String; enum CodingKeys: String, CodingKey { case id, title; case startDate = "start_date" } }
private struct TodayNote: Decodable, Identifiable { let id: UUID; let title: String; let reminderAt: String?; enum CodingKeys: String, CodingKey { case id, title; case reminderAt = "reminder_at" } }
private struct TodayPayment: Decodable, Identifiable { let id: UUID; let paymentType: String; let recipient: String; let reminderAt: String?; enum CodingKeys: String, CodingKey { case id; case paymentType = "payment_type"; case recipient; case reminderAt = "reminder_at" } }

struct TodayView: View {
    let onOpenCalls: () -> Void; let onOpenCalendar: () -> Void; let onOpenNotes: () -> Void; let onOpenPayments: () -> Void
    @State private var calls: [TodayCall] = []; @State private var events: [TodayEvent] = []; @State private var notes: [TodayNote] = []; @State private var payments: [TodayPayment] = []
    var body: some View { NavigationStack { List { Section { Text("Oggi").font(.largeTitle.weight(.black)); Text("Le cose da gestire entro domani.").foregroundStyle(Color(hex: "#716a91")) }.listRowBackground(Color.clear); Section("Richiami") { ForEach(calls.filter { $0.followUp }) { call in Button { onOpenCalls() } label: { Label("Richiamare \(call.callerName)", systemImage: "phone.fill") } } }; Section("Calendario") { ForEach(events) { event in Button { onOpenCalendar() } label: { Label(event.title, systemImage: "calendar") } } }; Section("Note") { ForEach(notes.filter { $0.reminderAt != nil }) { note in Button { onOpenNotes() } label: { Label(note.title, systemImage: "note.text") } } }; Section("Pagamenti") { ForEach(payments.filter { $0.reminderAt != nil }) { payment in Button { onOpenPayments() } label: { Label("\(payment.paymentType) · \(payment.recipient)", systemImage: "creditcard") } } } }.scrollContentBackground(.hidden).background(Color(hex: "#efe8d8")).task { await load() } } }
    private func load() async { do { async let c: [TodayCall] = SupabaseService.shared.from("calls").select().execute().value; async let e: [TodayEvent] = SupabaseService.shared.from("events").select().execute().value; async let n: [TodayNote] = SupabaseService.shared.from("notes").select().execute().value; async let p: [TodayPayment] = SupabaseService.shared.from("payments").select().execute().value; calls = try await c; events = try await e; notes = try await n; payments = try await p } catch {} }
}